# -*- coding: utf-8 -*-
"""06_newton_method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssN7ASxrfp6UtEfwtVSCj_Hj-kwZwNCb
"""

#define function
class function(object):
  def __init__(self,x):
    self.x=x
  def f(self,x):
    return x**3+3*x**2+3
  def df(self,x):
    return 3*x**2+6*x

#define a function that creates tangent
def tan(f,x1,x):
  y1=f.f(x1)
  m=f.df(x1)
  return m*(x-x1)+y1

def learn(f, x_ini, tolerance, epoch):
  x1 = x_ini
  history = {'x': [], 'y': [], 'm': []}
  print(f"{'Iteration':<10} {'x1 (Current Guess)':<20} {'f(x1)':<15}")
  print("-" * 50)
  for i in range(epoch):
    y1 = f.f(x1)
    m = f.df(x1)

    history['x'].append(x1)
    history['y'].append(y1)
    history['m'].append(m)

    print(f"{i:<10} {x1:<20.6f} {y1:<15.6f}")
    if abs(y1) < tolerance:
      return x1, history
    if m == 0:
      print("Slope is zero. Newton's Method failed.")
      return None, history
    x1 = x1 - y1 / m
  return x1, history

func_instance = function(3.0)

root, history = learn(func_instance, 3.0, 1e-16, 500)
print("-" * 50)
print(f"Final Root Found: {root:.6f}")

"""### Visualize Newton's Method Animation"""
import matplotlib
matplotlib.use('TkAgg')
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

x_vals = np.linspace(-4, 4, 400)
y_vals = func_instance.f(x_vals)

fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor("#000000")
ax.set_facecolor("#716D3C")
ax.plot(x_vals, y_vals, label='f(x) = x\u00b3 + 3x\u00b2 + 3', color='blue', linewidth=2)
ax.axhline(0, color='black', linestyle='-', linewidth=0.8)
ax.set_title("Newton's Method Step-by-Step Visualization")
ax.set_xlabel("x")
ax.set_ylabel("f(x)")
ax.grid(True, linestyle=':', alpha=0.6)

# Dynamic points
curr_point, = ax.plot([], [], 'ro', markersize=8, label='Current Guess')
next_point, = ax.plot([], [], 'go', markersize=8, label='New Guess')

# Dynamic lines
tangent_line, = ax.plot([], [], 'r--', linewidth=1.5, label='Tangent Line')
vertical_line, = ax.plot([], [], 'g:', linewidth=1.5, label='Vertical Step to Curve')

ax.legend(loc='upper left')

def animate(i):
    x_i = history['x'][i]
    y_i = history['y'][i]
    m_i = history['m'][i]
    
    # Update current point on the function
    curr_point.set_data([x_i], [y_i])
    
    # If it's the last frame, just keep the point and clear lines
    if i == len(history['x']) - 1:
        tangent_line.set_data([], [])
        vertical_line.set_data([], [])
        next_point.set_data([], [])
        return curr_point, tangent_line, vertical_line, next_point

    # Calculate the next step intersection with x-axis
    x_next = history['x'][i + 1]
    y_next = history['y'][i + 1]

    # Tangent line goes from current point (x_i, y_i) to x-axis intercept (x_next, 0)
    tangent_x = [x_i, x_next]
    tangent_y = [y_i, 0]
    tangent_line.set_data(tangent_x, tangent_y)
    
    # Update the green point showing the new guess on the x-axis
    next_point.set_data([x_next], [0])

    # Vertical line goes from x-axis intercept (x_next, 0) up/down to the function (x_next, y_next)
    vert_x = [x_next, x_next]
    vert_y = [0, y_next]
    vertical_line.set_data(vert_x, vert_y)

    return curr_point, tangent_line, vertical_line, next_point

ani = animation.FuncAnimation(
    fig, animate, frames=len(history['x']), interval=1500, blit=True, cache_frame_data=False
)

plt.show(block=True)